# -*- coding: utf-8 -*-
"""HW 1 (YOLOv8 - Ultralytics - Classification)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1697jgs29AV7qQK9hRmyoe1Bx1zaEvvL4
"""

# Import DATASET
DATA_DIR = '/content/drive/MyDrive/Kalbe/weather_dataset/'

# Instal ultralytics
!pip install ultralytics

#TRAINING MODEL
import os

from ultralytics import YOLO


# Load a model
model = YOLO("yolov8n-cls.pt")  # load a pretained model

# Use the model
results = model.train(data=DATA_DIR, epochs=20, imgsz=64)  # train the model

!scp -r /content/runs '/content/drive/MyDrive/Kalbe'

#VALIDATING MODEL
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n-cls.pt')  # load an official model
model = YOLO('/content/runs/classify/train3/weights/best.pt')  # load a custom model

# Validate the model
metrics = model.val()  # no arguments needed, dataset and settings remembered
metrics.top1   # top1 accuracy
metrics.top5   # top5 accuracy

!scp -r /content/runs '/content/drive/MyDrive/Kalbe'

#PREDICTING IMAGE
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n-cls.pt')  # load an official model
model = YOLO('/content/runs/classify/train3/weights/best.pt')  # load a custom model

# Predict with the model
results = model('/content/drive/MyDrive/Kalbe/weather_dataset/train/shine/shine111.jpg')  # predict on an image

from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n-cls.pt')  # load an official model
model = YOLO('/content/runs/classify/train3/weights/best.pt')  # load a custom model

# Predict with the model
results = model('/content/drive/MyDrive/Kalbe/hujan.jpg')  # predict on an image

from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n-cls.pt')  # load an official model
model = YOLO('/content/runs/classify/train3/weights/best.pt')  # load a custom model

# Predict with the model
results = model('/content/drive/MyDrive/Kalbe/mterbit.jpg')  # predict on an image

# EXPORT TO ONNX MODEL
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n-cls.pt')  # load an official model
model = YOLO('/content/runs/classify/train3/weights/best.pt')  # load a custom trained model

# Export the model
model.export(format='onnx')

!scp -r /content/runs '/content/drive/MyDrive/Kalbe'